# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Write-Up
tagline:             '好記性不如爛筆記'
description:         'My Personal Tech Blog'
url:                 http://lanyon.getpoole.com
baseurl:             'https://caesernieh.github.io'
paginate:            5

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

gems:           [jekyll-paginate]
