# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Write-Up
tagline:             '好記性不如爛筆記'
description:         'My Personal Tech Blog'
url:                 http://lanyon.getpoole.com
baseurl:             
paginate:            5

# About/contact
author:
  name:              Caeser Nieh
  url:               N/A
  email:             nieh821130@gmail.com

# Custom vars
version:             1.0.0

gems:           [jekyll-paginate]
